import { Mountain } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-slate-800 px-6 py-4">
        <Link href="/" className="flex items-center gap-2 text-amber-400 w-fit">
          <Mountain size={20} />
          <span className="font-display font-bold">YatraAI</span>
        </Link>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-12 font-body text-sm text-slate-700 leading-relaxed">
        <h1 className="text-3xl font-display font-bold text-foreground mb-8">Terms of Service</h1>
        <p className="text-slate-500 mb-8">Last updated: June 2026</p>

        <section className="mb-8">
          <h2 className="text-xl font-display font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using YatraAI, you agree to be bound by these Terms of Service.
            If you do not agree, please do not use the service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-display font-semibold text-foreground mb-3">2. Description of Service</h2>
          <p className="mb-3">
            YatraAI provides AI-powered travel safety assessments, route planning, real-time
            hazard alerts, and emergency notification services for travellers in Nepal.
          </p>
          <p>
            Safety scores and recommendations are generated by AI models and should be used
            as advisory information only. They do not guarantee absolute safety.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-display font-semibold text-foreground mb-3">3. User Obligations</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Provide accurate account information and keep it up to date</li>
            <li>Maintain the confidentiality of your account credentials</li>
            <li>Use the service responsibly and in compliance with applicable laws</li>
            <li>Not misuse the SOS system or submit false emergency alerts</li>
            <li>Not attempt to bypass rate limits, scrape data, or disrupt the service</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-display font-semibold text-foreground mb-3">4. Disclaimer of Warranties</h2>
          <p className="mb-3">
            YatraAI provides travel safety information on an &quot;as is&quot; and &quot;as available&quot; basis.
            We make no representations or warranties of any kind, express or implied, regarding
            the accuracy, reliability, or completeness of safety assessments, route
            recommendations, or hazard alerts.
          </p>
          <p className="mb-3">
            Travel in Nepal involves inherent risks including but not limited to changing
            weather conditions, natural disasters, road conditions, and political situations.
            YatraAI is not a substitute for:
          </p>
          <ul className="list-disc pl-6 space-y-1 mb-3">
            <li>Official government travel advisories</li>
            <li>Professional guide services</li>
            <li>Weather forecasts from the Nepal Department of Hydrology and Meteorology</li>
            <li>Medical advice from qualified healthcare providers</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-display font-semibold text-foreground mb-3">5. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, YatraAI and its operators shall not be
            liable for any direct, indirect, incidental, special, consequential, or punitive
            damages arising from your use of or inability to use the service, including but
            not limited to personal injury, property damage, or financial loss incurred
            during travel.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-display font-semibold text-foreground mb-3">6. Emergency SOS</h2>
          <p className="mb-3">
            The SOS feature is provided as a convenience tool to notify your designated
            emergency contacts. It does not directly notify emergency services (police,
            ambulance, or disaster response authorities).
          </p>
          <p>
            In a life-threatening emergency, always dial the Nepal emergency number (100 for
            police, 101 for fire, 102 for ambulance) before or in addition to using the SOS
            feature.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-display font-semibold text-foreground mb-3">7. Governing Law</h2>
          <p>
            These terms are governed by the laws of Nepal. Any disputes shall be resolved
            in the courts of Kathmandu, Nepal.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-display font-semibold text-foreground mb-3">8. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Users will be notified
            of material changes via email or in-app notification. Continued use after
            changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-display font-semibold text-foreground mb-3">9. Contact</h2>
          <p>
            For questions about these terms, contact us at{" "}
            <a href="mailto:legal@yatraai.com" className="text-amber-400 hover:underline">
              legal@yatraai.com
            </a>.
          </p>
        </section>
      </main>
    </div>
  );
}
